service: Lambda-S3-APIGateway-App

frameworkVersion: "3"

useDotenv: true

custom:
  dotenv:
    path: .env
  
provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_REGION}
  stage: dev
  timeout: 15
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::my-lmb-bucket/*"

functions:
  myFunction:
    handler: handler.handlerFunction
    url: true
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      NODE_ENV: "Development"
      TEST: "This is environment variable testing"
      S3_BUCKET_NAME: my-lmb-bucket

